import mongoose, { Schema, model } from 'mongoose';


const subscriptionSchema = new Schema({
    // _id is automatically generated by Mongoose
    adminId: {
        type: Schema.Types.ObjectId,
        ref: 'User', // Reference to the admin user who owns this subscription
        required: true,
        index: true
    },
    plan: {
        type: String,
        enum: ['basic', 'premium', 'enterprise'],
        required: true,
        default: 'basic'
    },
    features: {
        listingLimit: { type: Number, default: 0 },
        commissionRate: { type: Number, default: 0 },
        featuredListings: { type: Boolean, default: false },
        prioritySupport: { type: Boolean, default: false },
        analytics: { type: Boolean, default: false }
    },
    pricing: {
        type: Number,
        required: true,
        min: 0
    },
    startDate: {
        type: Date,
        required: true,
        default: Date.now
    },
    endDate: {
        type: Date,
        required: true
    },
    status: {
        type: String,
        enum: ['active', 'expired', 'cancelled'],
        default: 'active',
        index: true
    },
    paymentHistory: [{
        amount: Number,
        date: { type: Date, default: Date.now },
        transactionId: String
    }],
    autoRenew: {
        type: Boolean,
        default: true
    }
}, {
    // Automatically manages 'createdAt' and 'updatedAt' fields
    timestamps: true
});

// Optimization: Index for status and endDate to help with expiration cron jobs
subscriptionSchema.index({ status: 1, endDate: 1 });

const Subscription = model('Subscription', subscriptionSchema);

export default Subscription;